import { writeFileSync } from 'node:fs';
import { WebSocket } from 'ws';
const SB = process.env.SB;
const t = (await (await fetch('http://127.0.0.1:9334/json/list')).json()).find(x=>x.type==='page');
const ws = new WebSocket(t.webSocketDebuggerUrl,{maxPayload:256*1024*1024});
let id=0; const w=new Map(); const errs=[];
ws.on('message',(r)=>{const m=JSON.parse(r);
  if(m.id&&w.has(m.id)){w.get(m.id)(m);w.delete(m.id);return;}
  if(m.method==='Runtime.exceptionThrown') errs.push((m.params.exceptionDetails?.exception?.description||'').slice(0,160));
});
await new Promise(r=>ws.on('open',r));
const cmd=(me,p={})=>new Promise((res,rej)=>{const i=++id;const to=setTimeout(()=>rej(new Error(me+' timeout')),60000);w.set(i,(x)=>{clearTimeout(to);x.error?rej(new Error(JSON.stringify(x.error))):res(x.result)});ws.send(JSON.stringify({id:i,method:me,params:p}))});
const ev=async(e)=>(await cmd('Runtime.evaluate',{expression:e,returnByValue:true,awaitPromise:true})).result?.value;
const shot=async(n)=>{const s=await cmd('Page.captureScreenshot',{format:'png'});writeFileSync(`${SB}/shots/${n}`,Buffer.from(s.data,'base64'));console.log('saved',n);};
const wait=(ms)=>new Promise(r=>setTimeout(r,ms));
const until=async(e,l,n=25)=>{for(let i=0;i<n;i++){if(await ev(e))return true;await wait(2000);}console.log('TIMEOUT:',l);return false;};
await cmd('Page.enable'); await cmd('Runtime.enable'); await cmd('DOM.enable'); await cmd('Network.enable');
await cmd('Network.setCacheDisabled',{cacheDisabled:true});
await cmd('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true});
await cmd('Page.reload',{ignoreCache:true});
await until(`[...document.querySelectorAll('.rt')].some(x=>x.textContent.trim()==='haseeb')`,'machines');
console.log('engine marks in sidebar/home:', await ev(`document.querySelectorAll('.mark svg').length`));
console.log('notifications section:', await ev(`[...document.querySelectorAll('.section')].map(e=>e.textContent).join(' | ')`));
await shot('g1-home.png');
await ev(`(()=>{const e=[...document.querySelectorAll('.rt')].find(x=>x.textContent.trim()==='haseeb'); e?.closest('button')?.click();})()`);
await until(`document.querySelectorAll('.mark svg').length>0 && !!document.querySelector('.usage-row')`,'machine view');
console.log('marks on machine view:', await ev(`document.querySelectorAll('.mark svg').length`));
await shot('g2-machine.png');
await ev(`(()=>{const e=[...document.querySelectorAll('.rt')].find(x=>x.textContent.trim()==='helm-image-check'); e?.closest('button')?.click();})()`);
await until(`!!document.querySelector('.slab textarea')`,'session');
await wait(3000);
// the palette
await ev(`(()=>{const ta=document.querySelector('.slab textarea');
  const set=Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype,'value').set;
  set.call(ta,'/'); ta.dispatchEvent(new Event('input',{bubbles:true}));})()`);
await wait(1500);
console.log('palette entries:', await ev(`[...document.querySelectorAll('.palette .pname')].map(e=>e.textContent).join(' ')`));
await shot('g3-palette.png');
console.log('exceptions:', errs.slice(0,4));
ws.close(); process.exit(0);
