import { WebSocket } from 'ws';
const SB = process.env.SB;
const t = (await (await fetch('http://127.0.0.1:9334/json/list')).json()).find(x=>x.type==='page');
const ws = new WebSocket(t.webSocketDebuggerUrl,{maxPayload:256*1024*1024});
let id=0; const w=new Map();
ws.on('message',(r)=>{const m=JSON.parse(r); if(m.id&&w.has(m.id)){w.get(m.id)(m);w.delete(m.id);}});
await new Promise(r=>ws.on('open',r));
const cmd=(me,p={})=>new Promise((res,rej)=>{const i=++id;const to=setTimeout(()=>rej(new Error(me+' timeout')),90000);w.set(i,(x)=>{clearTimeout(to);x.error?rej(new Error(JSON.stringify(x.error))):res(x.result)});ws.send(JSON.stringify({id:i,method:me,params:p}))});
const ev=async(e)=>(await cmd('Runtime.evaluate',{expression:e,returnByValue:true,awaitPromise:true})).result?.value;
const wait=(ms)=>new Promise(r=>setTimeout(r,ms));
const until=async(e,l,n=25)=>{for(let i=0;i<n;i++){if(await ev(e))return true;await wait(2000);}console.log('TIMEOUT:',l);return false;};
await cmd('Page.enable'); await cmd('Runtime.enable'); await cmd('Network.enable');
await cmd('Network.setCacheDisabled',{cacheDisabled:true});
await cmd('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true});
await cmd('Page.reload',{ignoreCache:true});
await until(`[...document.querySelectorAll('.rt')].some(x=>x.textContent.trim()==='haseeb')`,'machines');
await ev(`(()=>{const e=[...document.querySelectorAll('.rt')].find(x=>x.textContent.trim()==='haseeb'); e?.closest('button')?.click();})()`);
await until(`!!document.querySelector('.sub')`,'machine view');
await wait(9000);
console.log('header:', await ev(`document.querySelector('.sub')?.innerText?.replace(/\\n/g,' ')`));
// the VM too, for contrast
await ev(`(()=>{const b=document.querySelector('.main .iconbtn, .main button'); })()`);
ws.close(); process.exit(0);
