import { readFileSync } from 'node:fs';
import { WebSocket } from 'ws';
const SB = process.env.SB;
const url = readFileSync(`${SB}/pairurl.txt`,'utf8').trim();
const t = (await (await fetch('http://127.0.0.1:9334/json/list')).json()).find(x=>x.type==='page');
const ws = new WebSocket(t.webSocketDebuggerUrl,{maxPayload:256*1024*1024});
let id=0; const w=new Map();
const logs=[], fails=[];
ws.on('message',(r)=>{const m=JSON.parse(r);
  if(m.id&&w.has(m.id)){w.get(m.id)(m);w.delete(m.id);return;}
  if(m.method==='Runtime.consoleAPICalled') logs.push(m.params.type+': '+(m.params.args||[]).map(a=>a.value??a.description??JSON.stringify(a.preview??'')).join(' '));
  if(m.method==='Runtime.exceptionThrown') logs.push('EXCEPTION: '+(m.params.exceptionDetails?.exception?.description||m.params.exceptionDetails?.text));
  if(m.method==='Network.loadingFailed') fails.push(m.params.errorText+' '+(m.params.type||''));
  if(m.method==='Network.responseReceived') { const r2=m.params.response; if(r2.status>=400) fails.push(r2.status+' '+r2.url); }
});
await new Promise(r=>ws.on('open',r));
const cmd=(me,p={})=>new Promise((res,rej)=>{const i=++id;const to=setTimeout(()=>rej(new Error(me+' timeout')),40000);w.set(i,(x)=>{clearTimeout(to);x.error?rej(new Error(JSON.stringify(x.error))):res(x.result)});ws.send(JSON.stringify({id:i,method:me,params:p}))});
const ev=async(e)=>(await cmd('Runtime.evaluate',{expression:e,returnByValue:true,awaitPromise:true})).result?.value;
await cmd('Page.enable'); await cmd('Runtime.enable'); await cmd('Network.enable');
await cmd('Network.setCacheDisabled',{cacheDisabled:true});
await cmd('Page.navigate',{url});
await new Promise(r=>setTimeout(r,9000));
console.log('location:', await ev('location.href'));
console.log('root html length:', await ev(`document.querySelector('#root')?.innerHTML.length ?? -1`));
console.log('scripts:', await ev(`[...document.querySelectorAll('script')].map(s=>s.src||'inline').join(' | ')`));
console.log('--- #root html ---');
console.log((await ev(`document.querySelector('#root')?.innerHTML`))?.slice(0,1200));
console.log('--- console ---'); logs.slice(0,15).forEach(l=>console.log(' ', l.slice(0,300)));
console.log('--- network failures ---'); [...new Set(fails)].slice(0,15).forEach(f=>console.log(' ', f.slice(0,200)));
ws.close(); process.exit(0);
