import { writeFileSync } from 'node:fs';
import { WebSocket } from 'ws';
const SB = process.env.SB;
const t = (await (await fetch('http://127.0.0.1:9334/json/list')).json()).find(x=>x.type==='page');
const ws = new WebSocket(t.webSocketDebuggerUrl,{maxPayload:256*1024*1024});
let id=0; const w=new Map();
ws.on('message',(r)=>{const m=JSON.parse(r); if(m.id&&w.has(m.id)){w.get(m.id)(m);w.delete(m.id);}});
await new Promise(r=>ws.on('open',r));
const cmd=(me,p={})=>new Promise((res,rej)=>{const i=++id;const to=setTimeout(()=>rej(new Error(me+' timeout')),60000);w.set(i,(x)=>{clearTimeout(to);x.error?rej(new Error(JSON.stringify(x.error))):res(x.result)});ws.send(JSON.stringify({id:i,method:me,params:p}))});
const ev=async(e)=>(await cmd('Runtime.evaluate',{expression:e,returnByValue:true,awaitPromise:true})).result?.value;
const shot=async(n)=>{const s=await cmd('Page.captureScreenshot',{format:'png'});writeFileSync(`${SB}/shots/${n}`,Buffer.from(s.data,'base64'));console.log('saved',n);};
const wait=(ms)=>new Promise(r=>setTimeout(r,ms));
const main=async(n=400)=>(await ev(`document.querySelector('.main')?.innerText`))?.replace(/\n+/g,' | ').slice(0,n);
await cmd('Page.enable'); await cmd('Runtime.enable'); await cmd('DOM.enable');

console.log('A click machine:', await ev(`(()=>{const e=[...document.querySelectorAll('.rt')].find(x=>x.textContent.trim()==='haseeb'); e?.closest('button')?.click(); return !!e;})()`));
await wait(5000); console.log('   main:', await main(200));
console.log('B click New session:', await ev(`(()=>{const b=[...document.querySelectorAll('.main button')].find(e=>e.textContent.trim()==='New session'); b?.click(); return !!b;})()`));
await wait(3000); console.log('   main:', await main(200));
console.log('C click folder:', await ev(`(()=>{const e=[...document.querySelectorAll('.main *')].find(x=>x.children.length===0&&x.textContent.trim()==='helm-image-check'); (e?.closest('button')||e)?.click(); return !!e;})()`));
await wait(2500); console.log('   main:', await main(200));
console.log('D click Start here:', await ev(`(()=>{const b=[...document.querySelectorAll('.main button')].find(e=>e.textContent.trim()==='Start here'); b?.click(); return !!b;})()`));
await wait(3000); console.log('   main:', await main(300));
console.log('E pick devin:', await ev(`(()=>{const e=[...document.querySelectorAll('.main *')].find(x=>x.children.length===0&&x.textContent.trim()==='devin'); (e?.closest('button')||e)?.click(); return !!e;})()`));
await wait(1500);
console.log('F start:', await ev(`(()=>{const b=[...document.querySelectorAll('.main button')].find(e=>e.textContent.trim().startsWith('Start Devin')); b?.click(); return !!b;})()`));
await wait(15000);
console.log('--- session ---'); console.log(await main(400));
console.log('clip:', await ev(`!!document.querySelector('button[title="attach image"]')`));
await shot('d2.png');
ws.close(); process.exit(0);
